apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/jparsai/application-api/config/crd?ref=64625654eab03c444d46ccdc755a1d5d67772d86
- https://github.com/codeready-toolchain/host-operator/config/crd?ref=826d3d5928fefa0105852bda895d326abefe992d
- ../../base
