# permissions for end users to view promotionruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promotionrun-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - promotionruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - promotionruns/status
  verbs:
  - get
