# permissions for end users to edit promotionruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promotionrun-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - promotionruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - promotionruns/status
  verbs:
  - get
