# permissions for end users to view snapshotenvironmentbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotenvironmentbinding-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshotenvironmentbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshotenvironmentbindings/status
  verbs:
  - get
