
apiVersion: v1
kind: Service
metadata:
  name: gitops-core-service-webhook-service
  namespace: gitops
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: appstudio-controller-manager
